### ISSUE TITLE
[Issue] Mandatory Dependency Not Documented

### ISSUE THREAD

**Issue by Sweek9** [SuperMartijn642/FormationsNether#2]
**Version Info**
- Minecraft v1.20.2
- Formations NOT DOCUMENTED
- Formations Overworld v1.0.2
- Forge v48.0.35

**Steps to Reproduce**
"Singleplayer"
"Create New Game"
It took me HOURS to figure out that it was your foundations mods that were causing the crash because nowhere on the CurseForge pages do they mention any dependencies, they don't tell Forge they have a dependency, and nothing in the log indicates which mod is causing the crash. The only way I found out that the library even exists is by searching the mods on CurseForge to report the crash. Obviously installing the library prevents the crash. You could save people a ton of grief by mentioning the required library on the mods page and properly marking the it as a dependency with Forge. 

**Crash report (~/logs/latest.log)**
```
[09Nov2023 21:12:57.681] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:450) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:90) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:197) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:196) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar%23130!/:build 13]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar%23142!/:build 13]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar%23130!/:build 13]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1238) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:781) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.main.Main.main(Main.java:221) ~[1.20.2-forge-48.0.35.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:98) ~[fmlloader-1.20.2-48.0.35.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:82) ~[fmlloader-1.20.2-48.0.35.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:17) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:40) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:58) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:96) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:13) ~[modlauncher-10.1.1.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:10) ~[modlauncher-10.1.1.jar:?]
	at net.minecraftforge.bootstrap.BootstrapLauncher.main(BootstrapLauncher.java:126) ~[bootstrap-1.2.0.jar:?]
Caused by: java.lang.IllegalStateException: Failed to load registries due to above errors
	at net.minecraft.resources.RegistryDataLoader.m_247207_(RegistryDataLoader.java:77) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.server.WorldLoader.m_246152_(WorldLoader.java:54) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.server.WorldLoader.m_245736_(WorldLoader.java:58) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:31) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232896_(CreateWorldScreen.java:126) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_279861_(SelectWorldScreen.java:55) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:38) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:41) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:164) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:93) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:443) ~[client-1.20.2-20230921.100330-srg.jar%23189!/:?]
	... 25 more
[09Nov2023 21:12:57.703] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 7518514e-2156-4a4f-ad71-67b78564ff8a
[09Nov2023 21:12:57.708] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID cebb0510-9df3-4dd3-b110-6a768a7e844d
```

**Comment by SuperMartijn642** [comment]
On the old CurseForge site, you can either click on the file you want to use:
![image](https://github.com/SuperMartijn642/FormationsNether/assets/12382965/63113f3a-ccc5-4f7f-92dd-20f81f80c19f)
Or on the 'relations' tab:
![image](https://github.com/SuperMartijn642/FormationsNether/assets/12382965/534907b3-07ea-4ffd-b8e4-0242ad48c98a)

On the new CurseForge site, you can click on the 'relations' tab:
![image](https://github.com/SuperMartijn642/FormationsNether/assets/12382965/0b125311-6cf4-4c21-bbca-2fc78555d75d)

The dependency is also marked in the `mods.toml` file for Forge. If Forge is not showing the dependency warning screen, that is likely caused by some other mod crashing when that screen is supposed to be shown.
A popular example of this is the mod Oculus, whenever the warning screen is supposed to shown, Oculus crashes the game.
